<input className="" type="text" name="categoryName"  placeholder="Add new category here" onChange={(e) => this.handleChange(e)} required />


            <option value="grapefruit">Grapefruit</option>
            <option value="lime">Lime</option>
            <option value="coconut">Coconut</option>
            <option value="mango">Mango</option>





                    let defaultCategories = this.state.categories.map((cat,i) => {
        return <option key={i} value="grapefruit">Grapefruit</option> });

        <form onSubmit={this.handleSubmit}>
          <select value={this.state.value} onChange={this.handleChange}>
            {defaultCategories}
          </select>

       </form>

       __________


       Category (Habit)
id (autogenerated)
name


User
id
name
email
userName
password
created_date
updated_date

PlanTracker
Date
Category
User
completed
